package site.ps2cpc.obs_websocket_remote_controller.enums;

public enum CommandEnum {

    PING_PONG,
    SLAVE_START_RECORDING,
    SLAVE_STOP_RECORDING,
    OBSERVER_STATUS_PREVIEW,
    OBSERVER_STATUS_PREVIEW_CLEAR,
    OBSERVER_STATUS_PLAYING,
    OBSERVER_STATUS_PLAYING_CLEAR,
    MINI_VIEW_ADD,
    MINI_VIEW_CLEAR,
    MINI_VIEW_CALLBACK,
    BROWSER_SOURCE_SHOW,
    BROWSER_SOURCE_HIDE,
}
